### ISSUE TITLE
Pdfx depends on device_info_plus

### ISSUE THREAD

**Issue by VersaDesenvolvimento** [ScerIO/packages.flutter#399]
Because pdfx >=2.0.1+3 <2.1.1 depends on device_info_plus ^3.2.4 and pdfx <2.0.1+3 depends on device_info_plus ^3.2.1, pdfx <2.1.1 requires device_info_plus ^3.2.1.
And because pdfx >=2.1.1 depends on device_info_plus ^4.0.0, every version of pdfx requires device_info_plus ^3.2.1 or ^4.0.0.

Current version of device_info_plus is 8.2.0

Could you update pdfx?

Thanks

Frederico Rodrigues

**Comment by Abdelazeem777** [comment]
I am facing the same conflict with upgrader package

**Comment by DJTB** [comment]
Same issue here, please update dependencies 🙏

**Comment by ItzDavi** [comment]
Facing this conflict too

**Comment by Abdelazeem777** [comment]
I found out that the device_info version is already updated on the `main` branch but not published yet

so for now you can just use it like this

```yaml
pdfx:
    git:
      url: "https://github.com/ScerIO/packages.flutter"
      path: packages/pdfx
```
