### ISSUE TITLE
Type 'DecoderCallback' not found In flutter 3.16

### ISSUE THREAD

**Issue by jahnli** [ScerIO/packages.flutter#448]
**Describe the bug**

```
/E:/pub-cache/hosted/pub.flutter-io.cn/pdfx-2.5.0/lib/src/viewer/pdf_page_image_provider.dart:24:55: Error: Type 'DecoderCallback' not found.
  ImageStreamCompleter load(PdfPageImageProvider key, DecoderCallback decode) =>
```

**Comment by erlangparasu** [comment]
got same issue

**Comment by JgomesAT** [comment]
We can compile flutter by fault of this any solution?

**Comment by jahnli** [comment]
This is my solution, I am not sure if it is suitable, but I was able to compile successfully

https://github.com/ScerIO/packages.flutter/pull/449

**Comment by erlangparasu** [comment]
Thanks @jahnli

This is my current temporary solution using @jahnli PR : 
File: pubspec.yaml
```yaml
  # pdfx: ^2.5.0
  pdfx:
    git:
      url: 'https://github.com/ScerIO/packages.flutter'
      ref: '4be9de9ffed5398fd7d5f44bbb07dcd3d3f1711b'
      path: packages/pdfx
```
